### ISSUE TITLE
Consider if we want to standardize non-actions

### ISSUE THREAD

**Issue by jdhoffa** [RMI-PACTA/demo_actions#29]
More things than just actions live in `.github`. For example, an issue template?

@AlexAxthelm please remove this if it is out of scope :-) just wanted to see if we want to consider this.

**Comment by AlexAxthelm** [comment]
I think this is worth visiting, but out of scope for this repo.

**Comment by jdhoffa** [comment]
Note: there's another duplicate repo that sorta covers this:
https://github.com/RMI-PACTA/.github
