### ISSUE TITLE
A test issue that was created on GitHub

### ISSUE THREAD

**Issue by jdhoffa** [RMI-PACTA/demo_actions#37]
This issue was created on GitHub in the https://github.com/RMI-PACTA/demo_actions/ repository. 
Using a GitHub action in the `demo_actions` repository, I am automatically adding this issue as a "Product Backlog Item" to the area path: "2DegreesInvesting\Test Team 1".

My suggestion for how we may use this in the tech team:
* Each software developer that is a maintainer would get their own area path on ADO, e.g. "@jdhoffa's maintainer backlog"
* The maintainer would then, optionally, add this action to all repositories that they maintain
* After that point, it would be the maintainer's responsibility to decide how to triage that issue (e.g. decide if it should stay in that area path, or if they with to move it under a specific scrum team, under a specific Epic, Feature, etc.)

**Comment by cjyetman** [comment]
Could you make it post a comment in the GH thread with a link to the ADO ticket that was created, partially as a reminder that there is a parallel ADO ticket that is related, and partially as a convenience to find that ADO ticket quickly?

**Comment by jdhoffa** [comment]
I will check if the action I am basing this off can do that by default. 
If not, I will see if I can work out how to do it myself :-)

**Comment by jdhoffa** [comment]
From what I can gather, this is not a default functionality of the action used (not terribly surprising). 

@cjyetman can you please point me to an action that you have written that automatically adds a comment to the issue? I will use that as a basis to try to get this functionality working.

**Comment by cjyetman** [comment]
Here's one example https://github.com/RMI-PACTA/workflow.transition.monitor/blob/main/.github/workflows/build-Docker-image-on-push-to-pr.yml

Now that I think about it, the hardest part might be getting the URL that ADO creates.

**Comment by jdhoffa** [comment]
Agreed, but I believe it is something returned by the action so may be accessible! I will give it a shot anyway if it's not difficult.

**Comment by cjyetman** [comment]
I know I'm late with this, but...

one idea to consider would be to only add to ADO when and ADO label is added (which I believe would also be triggered if you opened a new issue with the ADO tag)

that might make it easily manageable

**Comment by jdhoffa** [comment]
great minds think alike!

**Comment by jdhoffa** [comment]
See https://github.com/RMI-PACTA/demo_actions/issues/49
